### ISSUE TITLE
Refactor and prepare for V4

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/ocean-subgraph#208]
ToDO:

- [x] Implement global statistics
- [x] Implement roles
- [x] Order
- [x] Pool snapshot
- [x] Metadata Update -> Changed to NftUpdate
- [x] Fees: Pool and Datatoken (still thinking about the schema, will leave them at last)
- [x] check if the token templates are defined correctly in the yaml
- [x] Check schema and add comments to all fields (where it makes sense)
